In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as sio

In [ ]:
digits = sio.loadmat("/newfoundland/tarun/datasets/Digits/SVHN/extra_32x32.mat")

In [ ]:
train_digits = digits[0,0][0][0][0][0]
train_labels = digits[0,0][0][0][0][1]

test_digits = digits[0,0][1][0][0][0]
test_labels = digits[0,0][1][0][0][1]

unlabeled_images = np.concatenate([train_digits , test_digits] , 0)
unlabeled_labels = np.concatenate([train_labels , test_labels] , 0)

# all_padded_images = []
# for image in unlabeled_images:
#     image = image.reshape(28,28,1)
#     padded_image = np.zeros((32,32,1))
#     padded_image[2:-2 , 2:-2 , :] = image
#     all_padded_images.append(padded_image)
    
# unlabeled_images = np.stack(all_padded_images , 3)
# unlabeled_images = unlabeled_images.repeat(3,2)

unlabeled_images = unlabeled_images.transpose(1,0).reshape(28,28,1,-1)
unlabeled_labels = unlabeled_labels.transpose(1,0)

In [ ]:
unlabeled_images.shape

In [ ]:
rand_idx = np.random.choice(np.arange(unlabeled_images.shape[-1]))

print(rand_idx)
print("Label " , unlabeled_labels[:,rand_idx])

digits1 = unlabeled_images[:,:,:,rand_idx]
digits1 = digits1.repeat(3,2)
plt.imshow(digits1.astype('uint8'))
plt.show()

In [ ]:
sio.savemat("emnist.mat" , {"X":unlabeled_images , "y":unlabeled_labels})

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as sio

digits = sio.loadmat("/newfoundland/tarun/datasets/Digits/SVHN/extra_32x32.mat")

In [25]:
inputs = digits["X"]
gt_labels = digits["y"].astype(np.int64)
np.place(gt_labels, gt_labels == 10, 0)
labels = np.load("svhn_to_svhn_pseudo.np.npy")

In [37]:
(gt_labels == labels_noise_p).sum()/len(gt_labels)

0.8080473555488195

In [36]:
## Randomly flip x% of ids from labels
p = 20 ## percentage of noise
n = len(labels)
r_idxs = np.random.choice(np.arange(n) , size=(n*p//100,) , replace=False)
labels_noise_p = labels.copy()
noise = np.random.randint(0,9,(len(r_idxs),1))
labels_noise_p[r_idxs] = np.mod(labels_noise_p[r_idxs] + noise , 10)

In [19]:
r_idxs[:5]

array([497852,  11633, 260333, 345607,  83801])

In [20]:
print(labels[r_idxs[:5]].T)
print(noise[:5].T)
print(labels_noise_p[r_idxs[:5]].T)

[[2 9 1 3 2]]
[[4 3 0 3 4]]
[[6 2 1 6 6]]


In [38]:
sio.savemat("/newfoundland/tarun/datasets/Digits/svhn_noiseaug_20p.mat" , {"X":inputs , "y":labels_noise_p})

In [21]:
np.unique(labels_noise_p)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
labels_noise_p[r_idxs].shape

(5311, 1)

In [27]:
gt_labels.shape

(531131, 1)

In [11]:
labels.shape

(531131, 1)

In [9]:
labels_noise_p.shape

(531131, 1)

In [23]:
digits = sio.loadmat("/newfoundland/tarun/datasets/Digits/SVHN/syndigit_augmented_32x32.mat")

In [24]:
digits["y"].shape

(479400, 1)

In [10]:
inputs.shape

(32, 32, 3, 531131)